name: build

on: [push, workflow_call]

jobs:
    build:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install, dist
              run: |
                  npm ci
                  npm run dist
              env:
                  CI: true
