name: test

on:
    push:
        branches-ignore:
            - main
    workflow_call:

jobs:
    build:
        uses: ./.github/workflows/build.yml
    test:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [14.x]

        needs: [build]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install and test
              run: |
                  npm ci
                  npm run build
                  npm run test
              env:
                  CI: true
            - uses: actions/upload-artifact@v3
              with:
                  name: coverage
                  path: "./coverage"
                  if-no-files-found: error
